# Generated by Django 6.0.1 on 2026-04-20 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=20, verbose_name='Провайдер')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Сумма (тийин)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачено'), ('failed', 'Ошибка'), ('refunded', 'Возвращено')], default='pending', max_length=20, verbose_name='Статус')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=200, verbose_name='ID транзакции провайдера')),
                ('raw_request', models.JSONField(default=dict, verbose_name='Сырой запрос webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking', verbose_name='Бронирование')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
