# Generated by Django 6.0.1 on 2026-04-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Баланс (сум)'),
        ),
    ]
