# Generated by Django 6.0.1 on 2026-04-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('price_per_day', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Цена/день')),
                ('deposit_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Залог')),
                ('commission_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Комиссия платформы')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Итого')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('waiting_payment', 'Ожидает оплаты'), ('paid_escrow', 'Оплачено (эскроу)'), ('active', 'Активно (вещь у арендатора)'), ('returning', 'Возврат'), ('completed', 'Завершено'), ('dispute', 'Спор'), ('cancelled', 'Отменено')], default='created', max_length=20, verbose_name='Статус')),
                ('renter_comment', models.TextField(blank=True, verbose_name='Комментарий арендатора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('before', 'До передачи'), ('after', 'После возврата')], max_length=10, verbose_name='Тип')),
                ('image', models.ImageField(upload_to='protocols/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Фотопротокол',
                'verbose_name_plural': 'Фотопротоколы',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
