# Generated by Django 6.0.1 on 2026-04-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Доставщик',
                'verbose_name_plural': 'Доставщики',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA к арендатору'),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта доставки'),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота доставки'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA к владельцу'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Комиссия платформы (15%)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Ожидает оплаты'), ('placed', 'Заказ оформлен'), ('pickup_scheduled', 'Доставщик едет к владельцу'), ('picked_up', 'Доставщик забрал вещь'), ('active', 'Аренда активна'), ('completed', 'Аренда завершена'), ('cancelled', 'Отменено')], default='payment_pending', max_length=30, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='booking',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='bookings.deliverer', verbose_name='Доставщик'),
        ),
        migrations.DeleteModel(
            name='PhotoProtocol',
        ),
    ]
