# Generated by Django 6.0.1 on 2026-04-20 13:46

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_dates', models.JSONField(default=list, verbose_name='Заблокированные даты')),
            ],
            options={
                'verbose_name': 'Доступность',
                'verbose_name_plural': 'Доступность',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/', verbose_name='Изображение')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото объявления',
                'verbose_name_plural': 'Фото объявлений',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='Имя иконки или emoji', max_length=100, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_day', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Цена за сутки (сум)')),
                ('deposit', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Залог (сум)')),
                ('condition', models.CharField(choices=[('new', 'Новое'), ('excellent', 'Отличное'), ('good', 'Хорошее'), ('fair', 'Удовлетворительное')], default='good', max_length=20, verbose_name='Состояние')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('inactive', 'Неактивно'), ('moderation', 'На модерации')], default='moderation', max_length=20, verbose_name='Статус')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('city', models.CharField(default='Ташкент', max_length=100, verbose_name='Город')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
